### ISSUE TITLE
emitter Creation Rate not apparently affecting agent emission behavior

### ISSUE THREAD

**Issue by garthz** [lxfschr/Agent#18]
The Creation Rate parameter doesn't seem to have an effect on either the box, curve, or point emitters.

Example of expected behavior: setting particle lifespan of 100, creation rate at 4, maximum number of agents at 25, I would expect particles to be continuously emitted, one every four time steps.  E.g., the first particle would time out after 100 steps just after the 25th particle is emitted:

Actual behavior: even with creation rate greater than 1, one particle is emitted on every time step.  For the example parameters, a burst of 25 particles is emitted, followed by 75 steps without emission.

In each case, 'Continuous Flow' has the default True value.

**Comment by lxfschr** [comment]
Thanks for posting this. The bug fix will be included in the next release on Monday.
